### ISSUE TITLE
pip error ...please help

### ISSUE THREAD

**Issue by shariat1** [AndronixApp/AndronixOrigin#13]
i use kali. I install python pip. But when i type " pip -V " than show errror.

♦root@localhost:~# pip -V
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>    from pip._internal import main
  File "/usr/lib/python2.7/dist-packages/pip/_internal/__init__.py", line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
    vendored("colorama")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored                                           __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/__init__.py", line 2, in <module>
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/initialise.py", line 6, in <module>
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/ansitowin32.py", line 7, in <module>
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/winterm.py", line 2, in <module>
  File "/usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl/colorama/win32.py", line 8, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 556, in <module>
    _reset_cache()
  File "/usr/lib/python2.7/ctypes/__init__.py", line 276, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
root@localhost:~#
![Screenshot_20191103-152425](https://user-images.githubusercontent.com/43130959/68083148-b8559a00-fe4f-11e9-890f-7d36255cd0a5.png)

**Comment by ultrahacx** [comment]
We have provided other platforms to ask for help. This is not a right place to ask it by raising an issue. We cannot provide solution to every problem you have within linux and it is out of scope of our service too. Then also you can contact us on Discord to get help.
